spring:
  application:
    name: "server"
  datasource:
    url: jdbc:h2:file:./database/mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  banner:
    location=classpath:/banner.txt
