spring:
  application:
    name: "server"
  datasource:
    url: jdbc:h2:file:./database/mydb;AUTO_SERVER=TRUE;INIT=RUNSCRIPT FROM 'classpath:/database/data.sql'
    username: SA
    password: PASSWORD
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  banner:
    location: banner.txt
